/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as HoldRouteImport } from './routes/hold'
import { Route as ReworkRouteImport } from './routes/rework'
import { Route as RtsRouteImport } from './routes/rts'
import { Route as ScrapRouteImport } from './routes/scrap'
import { Route as InspectionIdRouteImport } from './routes/inspection/$id'
import { Route as NcrIndexRouteImport } from './routes/ncr/index'
import { Route as NcrIdRouteImport } from './routes/ncr/$id'
import { Route as NcrNewRouteImport } from './routes/ncr/new'
import { Route as QueueIndexRouteImport } from './routes/queue/index'
import { Route as QueueIdRouteImport } from './routes/queue/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldRoute = HoldRouteImport.update({
  id: '/hold',
  path: '/hold',
  getParentRoute: () => rootRouteImport,
} as any)
const ReworkRoute = ReworkRouteImport.update({
  id: '/rework',
  path: '/rework',
  getParentRoute: () => rootRouteImport,
} as any)
const RtsRoute = RtsRouteImport.update({
  id: '/rts',
  path: '/rts',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapRoute = ScrapRouteImport.update({
  id: '/scrap',
  path: '/scrap',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionIdRoute = InspectionIdRouteImport.update({
  id: '/inspection/$id',
  path: '/inspection/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NcrIndexRoute = NcrIndexRouteImport.update({
  id: '/ncr/',
  path: '/ncr/',
  getParentRoute: () => rootRouteImport,
} as any)
const NcrIdRoute = NcrIdRouteImport.update({
  id: '/ncr/$id',
  path: '/ncr/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NcrNewRoute = NcrNewRouteImport.update({
  id: '/ncr/new',
  path: '/ncr/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIdRoute = QueueIdRouteImport.update({
  id: '/queue/$id',
  path: '/queue/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/hold': typeof HoldRoute
  '/rework': typeof ReworkRoute
  '/rts': typeof RtsRoute
  '/scrap': typeof ScrapRoute
  '/inspection/$id': typeof InspectionIdRoute
  '/ncr/$id': typeof NcrIdRoute
  '/ncr/new': typeof NcrNewRoute
  '/queue/$id': typeof QueueIdRoute
  '/ncr/': typeof NcrIndexRoute
  '/queue/': typeof QueueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/hold': typeof HoldRoute
  '/rework': typeof ReworkRoute
  '/rts': typeof RtsRoute
  '/scrap': typeof ScrapRoute
  '/inspection/$id': typeof InspectionIdRoute
  '/ncr/$id': typeof NcrIdRoute
  '/ncr/new': typeof NcrNewRoute
  '/queue/$id': typeof QueueIdRoute
  '/ncr': typeof NcrIndexRoute
  '/queue': typeof QueueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/hold': typeof HoldRoute
  '/rework': typeof ReworkRoute
  '/rts': typeof RtsRoute
  '/scrap': typeof ScrapRoute
  '/inspection/$id': typeof InspectionIdRoute
  '/ncr/$id': typeof NcrIdRoute
  '/ncr/new': typeof NcrNewRoute
  '/queue/$id': typeof QueueIdRoute
  '/ncr/': typeof NcrIndexRoute
  '/queue/': typeof QueueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/hold'
    | '/rework'
    | '/rts'
    | '/scrap'
    | '/inspection/$id'
    | '/ncr/$id'
    | '/ncr/new'
    | '/queue/$id'
    | '/ncr/'
    | '/queue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/hold'
    | '/rework'
    | '/rts'
    | '/scrap'
    | '/inspection/$id'
    | '/ncr/$id'
    | '/ncr/new'
    | '/queue/$id'
    | '/ncr'
    | '/queue'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/hold'
    | '/rework'
    | '/rts'
    | '/scrap'
    | '/inspection/$id'
    | '/ncr/$id'
    | '/ncr/new'
    | '/queue/$id'
    | '/ncr/'
    | '/queue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  HoldRoute: typeof HoldRoute
  ReworkRoute: typeof ReworkRoute
  RtsRoute: typeof RtsRoute
  ScrapRoute: typeof ScrapRoute
  InspectionIdRoute: typeof InspectionIdRoute
  NcrIdRoute: typeof NcrIdRoute
  NcrNewRoute: typeof NcrNewRoute
  QueueIdRoute: typeof QueueIdRoute
  NcrIndexRoute: typeof NcrIndexRoute
  QueueIndexRoute: typeof QueueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hold': {
      id: '/hold'
      path: '/hold'
      fullPath: '/hold'
      preLoaderRoute: typeof HoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rework': {
      id: '/rework'
      path: '/rework'
      fullPath: '/rework'
      preLoaderRoute: typeof ReworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rts': {
      id: '/rts'
      path: '/rts'
      fullPath: '/rts'
      preLoaderRoute: typeof RtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scrap': {
      id: '/scrap'
      path: '/scrap'
      fullPath: '/scrap'
      preLoaderRoute: typeof ScrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection/$id': {
      id: '/inspection/$id'
      path: '/inspection/$id'
      fullPath: '/inspection/$id'
      preLoaderRoute: typeof InspectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ncr/': {
      id: '/ncr/'
      path: '/ncr'
      fullPath: '/ncr/'
      preLoaderRoute: typeof NcrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ncr/$id': {
      id: '/ncr/$id'
      path: '/ncr/$id'
      fullPath: '/ncr/$id'
      preLoaderRoute: typeof NcrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ncr/new': {
      id: '/ncr/new'
      path: '/ncr/new'
      fullPath: '/ncr/new'
      preLoaderRoute: typeof NcrNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/$id': {
      id: '/queue/$id'
      path: '/queue/$id'
      fullPath: '/queue/$id'
      preLoaderRoute: typeof QueueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  HoldRoute: HoldRoute,
  ReworkRoute: ReworkRoute,
  RtsRoute: RtsRoute,
  ScrapRoute: ScrapRoute,
  InspectionIdRoute: InspectionIdRoute,
  NcrIdRoute: NcrIdRoute,
  NcrNewRoute: NcrNewRoute,
  QueueIdRoute: QueueIdRoute,
  NcrIndexRoute: NcrIndexRoute,
  QueueIndexRoute: QueueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
